cask_args appdir: '/Applications'

brew 'imagemagick'
brew 'neovim'
brew 'openssl'
brew 'pass'
brew 'pandoc'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'zsh'

cask 'alfred'
cask 'firefox'
cask 'flux'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'iterm2'
cask 'opera'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'
